Fix missing dependency
Remove test scope from jackson-annotations to fix NoClassDefFoundError.
com/fasterxml/jackson/annotation/JsonView: java.lang.NoClassDefFoundError
java.lang.NoClassDefFoundError: com/fasterxml/jackson/annotation/JsonView
	at com.fasterxml.jackson.databind.introspect.JacksonAnnotationIntrospector.<clinit>(JacksonAnnotationIntrospector.java:35)
	at com.fasterxml.jackson.databind.ObjectMapper.<clinit>(ObjectMapper.java:283)
	at com.signalfx.connection.AbstractHttpReceiverConnection.<clinit>(AbstractHttpReceiverConnection.java:31)